### ISSUE TITLE
Good Script

### ISSUE THREAD

**Issue by cihanmehmet** [YashGoti/Subdomain#3]
It looks like script  below. (You should update rapiddns.io.) 😀
https://github.com/cihanmehmet/sub.sh

**Comment by YashGoti** [comment]
Yes it was inspired by your script @cihanmehmet 
TQ for that but I didn't understand why I should update rapiddns.io

**Comment by cihanmehmet** [comment]
You should update the rapiddns link. Because in this way, there are no more than 100 subdomains. If you want google.com

You can use it as below. 👍
```shell
curl -s "https://rapiddns.io/subdomain/$1?full=1#result"
```
Have a good day.

**Comment by YashGoti** [comment]
Hey thanks I updated it
BTW I didn't knew about it.
